name: github-runner-docker
on: [workflow_dispatch]
jobs:
  compile-service:
    runs-on: ubuntu-latest    
    container: maven:3-openjdk-8
    steps:
    - uses: actions/checkout@v3
    - run: mvn -f myservice install
