name: github-runner
on: [workflow_dispatch]
jobs:
  compile-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - run: mvn -f myservice install
